spring:
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: 2023
      timeout: 50000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
